import Provider from '@/context/context'
import './globals.css'
import Header from '@/components/Global/Header'

export const metadata = {
  title: 'FC FCSB SA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className='relative'> 
            <Header />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
