import Provider from '@/context/context'
import './globals.css'
import Header from '@/components/Global/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <main>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
